[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "pandadoc"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Vendor/PandaDoc", "Area/Productivity & Collaboration", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-pandadoc"

[build-options]
observabilityIncluded = true

